In [1]:
from blackjack.utils import create_deck, as_str
from blackjack.game import blackjack_card_value
from collections import defaultdict
import numpy as np

In [2]:
deck = create_deck()

In [43]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
series = np.random.choice(a, size=(3, 6), 
                 replace=True, 
                 p=[.2, .1, .1, .3, .1, .1, .1, 0])

In [88]:
series.T.shape

(6, 3)

In [90]:
series.T.mean(axis=1)

array([4.        , 5.33333333, 3.        , 5.        , 4.66666667,
       3.        ])

In [102]:
X = np.random.randint(0, 10, size=(3, 4))

In [103]:
series.T.dot(X)

array([[60, 67, 55, 56],
       [74, 83, 73, 72],
       [51, 41, 43, 56],
       [78, 75, 70, 80],
       [61, 76, 63, 56],
       [39, 32, 42, 48]])

In [54]:
m = np.array([
    [2, 3, 4],
    [5, 6, 6]
])

In [52]:
m

array([[2, 3, 4],
       [5, 6, 9]])